development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:48545c6bb070fbaee1efbfb2d35a74b8@dory.redistogo.com:11862/
  channel_prefix: stat-crew-api_production
